# Generated by Django 4.2.1 on 2023-06-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mettingIdx", models.IntegerField()),
                ("memberIdx", models.IntegerField()),
                ("content", models.CharField(max_length=200)),
                ("write_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
