# Generated by Django 4.2.1 on 2023-06-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="mettingIdx",
            field=models.ForeignKey(
                db_column="mettingIdx",
                on_delete=django.db.models.deletion.CASCADE,
                to="recruit.recruit",
            ),
        ),
    ]
