# Generated by Django 4.2.1 on 2023-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="like_category",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile",
            field=models.ImageField(
                blank=True, default=None, upload_to="member/images/%Y/%m/%d/"
            ),
        ),
    ]
