# Generated by Django 4.2.1 on 2023-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_alter_member_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="like_category",
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
