# Generated by Django 4.2.1 on 2023-06-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_alter_member_like_category_alter_member_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="identifier",
            new_name="memberId",
        ),
    ]
